#!/usr/bin/env bash

tar cfz ~/.vim_backup.tgz ~/.vim ~/.vimrc > /dev/null 2>&1
rm -rf ~/.vim ~/.vimrc
echo "backed up existing ~/.vim and ~/.vimrc to ~/.vim_backup.tgz"

git clone -q git://github.com/zentrification/vim.git /tmp/zentrification-vim 2> /dev/null
mv /tmp/zentrification-vim ~/.vim
ln -s ~/.vim/vimrc ~/.vimrc
echo "cloned repository to ~/.vim and symlinked ~/.vimrc"

cd ~/.vim
git submodule init > /dev/null 2>&1
git submodule update > /dev/null 2>&1
echo "git submodule init and update for vundle"
echo "now open vim and execute the command BundleInstall"
